### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by NanoBjorn**
Hello!

Wanted to render one page regularly and to avoid chromedriver struggles on any OS, so wrote a `docker/Dockerfile` and `docker-compose.yml`. Also added small instruction to readme.

P.S. Btw it seems that loconotion does not support Boards rendering. Tried mine and had very bad buggy page.

### CODE REVIEW

**Comment by leoncvlt** [comment]
Thanks for this! I don't have much experience with docker but it seems useful. Is the `PATH_TO_NOTION_FILE` you mention in the readme the .toml file, or does this support the "simple usage" caching passing the notion url as well?

**Comment by leoncvlt** [comment]
P.S. Also, do you have examples of pages which fail the boards rendering? Always useful to have a failing test case.

**Comment by philfreo** [comment]
This worked for me, thanks. Only surprising thing was that it defaulted to outputting in /tmp instead of ./dist/ by default.

Might want to either change that default path or else have the default example include passing an env var like `LOCONOTION_LOCAL_DIST=./dist docker-compose run loconotion https://www.notion.so/The-perfect-It-s-Always-Sunny-in-Philadelphia-episode-d08aaec2b24946408e8be0e9f2ae857e`

To take this further, it'd be great to see this merged and then have a Docker image pushed to Dockerhub. I think that would then enable a single command to run this without even having to have the locomotion git repo checked out locally at all. I'd love to run a single command (or docker-compose.yml file only) in my other GitHub repo that builds and outputs right there so I can just git push & host the HTML in GitHub Pages.

**Comment by philfreo** [comment]
@NanoBjorn what do you think about that?

As of now, I made a little script https://github.com/philfreo/sjc.vote/blob/main/update for a one liner to run which requires that this branch of loconotion is checked out in a sibling directory to my own static site. With the changes mentioned above I think this could be simplified.

**Comment by NanoBjorn** [comment]
I thought that for local use `/tmp/` by default is more safe location than `./dist`. I would better mention the env variable in the readme instead of changing the default.

**Comment by philfreo** [comment]
I disagree (since the output is the important artifact, not a 'temp' file), but I suppose that's @leoncvlt's call -- ultimately I'd be happy for this to get merged regardless and pushed to dockerhub.

**Pull request merged**
